// Package cfgwriter generates and edits the server.cfg that lives in
// server-data/. It writes a minimal, working default and knows how to
// inject specific values (i.e. cfx license key) into it
package cfgwriter

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// Options controls what gets written/injected.
type Options struct {
	License string
}

const defaultTemplate = `
########################################################################################
#                                                                                      #
#  .d888          888b     d888                                                        #
#  d88P"           8888b   d8888                                                       #
#  888             88888b.d88888                                                       #
#  888888 888  888 888Y88888P888  8888b.  88888b.   8888b.   .d88b.   .d88b.  888d888  #
#  888    'Y8bd8P' 888 Y888P 888     "88b 888 "88b     "88b d88P"88b d8P  Y8b 888P"    #
#  888      X88K   888  Y8P  888 .d888888 888  888 .d888888 888  888 88888888 888      #
#  888    .d8""8b. 888   "   888 888  888 888  888 888  888 Y88b 888 Y8b.     888      #
#  888    888  888 888       888 "Y888888 888  888 "Y888888  "Y88888  "Y8888  888      #
#                                                               888                    #
#                                                          Y8b d88P                    #
#                                                           "Y88P"                     #
#                                                                                      #
#   Generated by fxManager/cli-installer - edit freely, this file is not overwritten   #
#  ----------------------------------------------------------------------------------  #
#   More information on setting up a server:                                           #
#   * https://aka.cfx.re/server-commands                                               #
#   * https://docs.fivem.net/docs/server-manual/setting-up-a-server/                   #
########################################################################################

# Best not to touch these unless you know what you're doing
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

# These can be changed to your liking
%s
sv_maxclients 48            # still restricted by your Cfx subscription
# sv_master1 ""             # can be used to set the server as "private"
sets tags "fxmanager"
sets locale "root-AQ"
# load_server_icon icon.png # a 96px square png icon

sv_hostname "Hostname"
sets sv_projectName "A cool server"
sets sv_projectDescription "A cool server - Powered by fxManager"

# ┏━┓┏━╸┏━┓┏┳┓╻┏━┓┏━┓╻┏━┓┏┓╻┏━┓ #
# ┣━┛┣╸ ┣┳┛┃┃┃┃┗━┓┗━┓┃┃ ┃┃┗┫┗━┓ #
# ╹  ┗━╸╹┗╸╹ ╹╹┗━┛┗━┛╹┗━┛╹ ╹┗━┛ #

# any extra permissions that need to be granted, using the ace system
# fxManager already provides permissions for the panel to the players.
# When creating an admin, make sure you link a player account so he gets
# the permissions in game. Here are some examples:
#
# add_ace group.admin command allow
# add_ace group.admin command.quit deny              # don't allow them shutting the server down
# add_principal identifier.fivem:0000000 group.admin # grant a player the admin group permissions
# add_ace resource.ox_lib command.add_ace allow      # allow a resource to add ace permissions

# ┏━┓┏━╸┏━┓┏━┓╻ ╻┏━┓┏━╸┏━╸┏━┓ #
# ┣┳┛┣╸ ┗━┓┃ ┃┃ ┃┣┳┛┃  ┣╸ ┗━┓ #
# ╹┗╸┗━╸┗━┛┗━┛┗━┛╹┗╸┗━╸┗━╸┗━┛ #

# Don't ensure fxManager, it's already handled by the panel
# Start your resources using "start your_resource" below
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
`

const licenseLine = `sv_licenseKey "%s"`
const licenseLinePlaceholder = `# sv_licenseKey "REPLACE_WITH_YOUR_CFX_LICENSE_KEY"  # get one at https://portal.cfx.re/servers/registration-keys?modal=create`

var licenseLineRe = regexp.MustCompile(`(?m)^\s*#?\s*sv_licenseKey\s+".*"\s*$`)

// Write creates server.cfg at path if it doesn't exist yet, using the
// default template. If it already exists (e.g. re-running the
// installer against an existing server-data/), Write only touches the
// sv_licenseKey line via Inject, leaving everything else alone
func Write(path string, opts Options) error {
	if _, err := os.Stat(path); err == nil {
		return Inject(path, opts)
	}

	license := licenseLinePlaceholder
	if opts.License != "" {
		license = fmt.Sprintf(licenseLine, opts.License)
	}

	content := fmt.Sprintf(defaultTemplate, license)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// Inject replaces (or appends) the sv_licenseKey line in an existing
// server.cfg without touching anything else in the file. Safe to call
// even if opts.License is empty (it's then a no-op)
func Inject(path string, opts Options) error {
	if opts.License == "" {
		return nil
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}

	newLine := fmt.Sprintf(licenseLine, opts.License)

	var out string
	if licenseLineRe.MatchString(string(raw)) {
		out = licenseLineRe.ReplaceAllString(string(raw), newLine)
	} else {
		out = strings.TrimRight(string(raw), "\n") + "\n\n" + newLine + "\n"
	}

	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
